# Generated by Django 4.1.2 on 2022-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
