# Generated by Django 4.1.2 on 2022-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_booking_cinemahall_genre_movie_show_ticket_showseat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link_trailer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
