# Generated by Django 4.1.2 on 2022-12-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_movie_link_trailer_alter_showseat_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='end_hour',
        ),
    ]
