# Generated by Django 4.1.2 on 2022-12-28 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
