# Generated by Django 4.1.2 on 2022-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_sitesettings_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_status',
            field=models.BooleanField(default=True),
        ),
    ]
